name: Deploy Terraform with Approval

on:
  pull_request:
    types:
      - closed  # Solo cuando el PR se cierra
    paths:
      - '**/*.tf'  # Detecta cambios en archivos .tf.

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  DEPLOY:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Detectar carpeta basada en el nombre de la rama
      - name: Detect Directory from Branch Name
        id: detect-dir
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == tf/* ]]; then
            DIR_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's#^tf/##')
            echo "directory=$DIR_NAME" >> $GITHUB_ENV
          else
            echo "Branch name '${{ github.event.pull_request.head.ref }}' does not follow the 'tf/' convention."
            exit 1
          fi

      # Paso 3: Verificar y listar contenido del directorio
      - name: Check and List Directory
        run: |
          echo "Directory: ${{ env.directory }}"
          ls -la ${{ env.directory }}

      # Paso 4: Configurar AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377079132:role/access-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      # Paso 5: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Paso 6: Inicializar Terraform
      - name: Terraform Init
        run: |
          cd ${{ env.directory }}
          terraform init

      # Paso 7: Validar configuración de Terraform
      - name: Validate Terraform
        run: |
          cd ${{ env.directory }}
          terraform validate

      # Paso 8: Generar el plan
      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ env.directory }}
          terraform plan -out=tfplan

      # Paso 9: Subir el archivo del plan como artefacto
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ${{ env.directory }}/tfplan

  APPLY:
    runs-on: ubuntu-latest
    needs: DEPLOY
    if: success()  # Solo estará disponible si DEPLOY fue exitoso
    environment: apply-tf

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 3: Configurar AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377079132:role/access-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      # Paso 4: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Paso 5: Aplicar el plan
      - name: Terraform Apply
        run: |
          cd ${{ env.directory }}
          terraform apply -auto-approve


  DESTROY:
    runs-on: ubuntu-latest
    needs: DEPLOY
    if: success()  # Solo estará disponible si DEPLOY fue exitoso
    environment: destroy-tf

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377079132:role/access-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd ${{ env.directory }}
          terraform init

      - name: Terraform Destroy
        run: |
          cd ${{ env.directory }}
          terraform destroy -auto-approve
