name: Deploy to Production

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: producción  # Nombre del environment configurado en GitHub
      url: ${{ steps.deployment.outputs.page_url }}  # URL opcional para monitoreo o información adicional

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Cambia a la versión de Terraform que necesitas
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Paso 3: Formatear el código de Terraform
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # Paso 4: Inicializar Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Paso 5: Validar el código de Terraform
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Paso 6: Planificar el despliegue de Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true

      # Paso 7: Mostrar el plan de Terraform
      - name: Show Plan
        uses: actions/github-script@v6
        if: steps.plan.outcome == 'success'
        with:
          script: |
            const output = require('@actions/core').setOutput;
            const plan = require('fs').readFileSync('tfplan', 'utf8');
            output('plan', plan);

      # Paso 8: Solicitar aprobación del equipo antes de aplicar el despliegue
      - name: Await approval
        uses: actions/github-script@v6
        if: steps.plan.outcome == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewers = ['Infraestructura'];  # Reemplaza con el nombre del equipo creado
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              team_reviewers: reviewers,
            });

      # Paso 9: Aplicar el plan de Terraform tras la aprobación
      - name: Terraform Apply
        if: github.event.review.state == 'approved'
        run: terraform apply "tfplan"

      # Paso 10: Aplicación automática tras push en main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      # Paso 11: Merge automático tras éxito y aprobación
      - name: Success-merge
        if: steps.apply.outcome == 'success' && github.event.review.state == 'approved'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.deployment.environment }}
          head: ${{ github.ref_name }}
          commit_message: 'Merge automático desde la rama ${{ github.ref_name }}'
